### ISSUE TITLE
Make json adapter pluggable

### ISSUE THREAD

**Issue by rauanmayemir** [andersfugmann/ocaml-protoc-plugin#17]
I've been playing with the latest changes on the repo and discovered yojson is now a hard dependency which is problematic for web runtimes like melange, a bucklescript successor (I know, I know, but this one is close to ocaml and is here to stay 😄).

It would be nice to have json serializer be pluggable and setting it via ocaml_opt sounds like a good option.

**Comment by andersfugmann** [comment]
Never thought of this problem, as I though `Yojson` is more or less standard for Json handling in ocaml. 
What do Melange users use for json handling? 

I could add an option for code generation to not emit json serialization / deserialization functions, and place the json runtime support in a separate (optional) package - But that feels somewhat awkward, as codegen and the runtime is to tightly coupled.

**Comment by andersfugmann** [comment]
> setting it via ocaml_opt sounds like a good option

Can you expand on this solution?

**Comment by rauanmayemir** [comment]
By option I meant something like ‘ocaml_opt=json_adapter=yojson’, but it was not an educated suggestion.

I used to use atdgen, but now I mainly use protobuf in binary mode. https://github.com/melange-community/melange-json would probably be a go-to option for handling json.

I agree that it feels awkward to split it out, but from a perspective of bundling it for browser it makes more sense for leaner output.

**Comment by andersfugmann** [comment]
I actually don't think it would be that hard to remove all runtime dependencies to `yojson`. The system just needs to define the json type, which is already using polymorphic variants. The only disadvantage is that the function signature will bot reference `Yojson.Basic.t`, but that's a minor issue. 
 
Let me try it out.

**Comment by andersfugmann** [comment]
PR #19 removes runtime dependency on package yojson. (still needed for tests though). Would that work for melange?

**Comment by rauanmayemir** [comment]
I think it will work nicely, I’ll try these changes when I get back to the keyboard.

**Comment by andersfugmann** [comment]
Just pushed an update to remove the last references to Yojson on the branch. 

Btw. Does melange not eliminate dead code? Are there any observable changes to size when including the Yojson library for melange builds? 

Documentation would be much more easy to understand if the type used for Json serialization and deserialization is `Yojson.Basic.t` rather than local `Json.t`. I can remove all other references to Yojson to avoid pulling in larger dependencies.

**Comment by rauanmayemir** [comment]
It's not about the build size, but the need to 'fork wrap' yojson alongside all of its dependencies so that their dune config has `(modes melange)` stanza. I suggested doing it because ATD does exactly that: it has an abstract `Json.t` that gets expanded by the runtime lib. It looks like it uses melange-json: https://github.com/ahrefs/melange-atdgen-codec-runtime

Melange itself would not eliminate, but I believe bundler would, although I can't be sure.

**Comment by rauanmayemir** [comment]
I've tried your changes locally and now the code at least won't break because of `yojson` dep. I'll be happy to tinker the melange runtime lib part some time later.
