### ISSUE TITLE
Empty messages will lead to uncompilable code generation with `singleton_record=true`

### ISSUE THREAD

**Issue by rauanmayemir** [andersfugmann/ocaml-protoc-plugin#20]
If proto message definition has no fields, then the generated code will not be compilable on OCaml 5.1.1:

```
(* ... *)
          let merge =
            fun t1 t2 -> {

             }
(* ... *)
```

build error:
```
1125 |             }
                      ^
Error: Syntax error
```

Simplest example: `google/protobuf/empty.proto` is not compilable due to this syntax error.

**Comment by rauanmayemir** [comment]
I think this is reproducable with `singleton_record=true`.

**Comment by andersfugmann** [comment]
Thanks for reporting. I think I need to expand tests to verify code emissions with different combination of code-gen flags.
