### ISSUE TITLE
Handle referencing multiple identically named proto files

### ISSUE THREAD

**Issue by andersfugmann** [andersfugmann/ocaml-protoc-plugin#7]
Copy from [initial issue](https://github.com/issuu/ocaml-protoc-plugin/issues/51):

@vbmithr
For example:

```
import "temporal/api/enums/v1/workflow.proto";
import "temporal/api/common/v1/message.proto";
import "temporal/api/failure/v1/message.proto";
import "temporal/api/taskqueue/v1/message.proto";
```

Would generate a caml file with 3 times `Message = Message` lines generated, which is incorrect.

---
@vbmithr
For instance, a protobuf like this 

```protobuf
syntax = "proto3";

package temporal.api.workflow.v1;

option go_package = "go.temporal.io/api/workflow/v1;workflow";
option java_package = "io.temporal.api.workflow.v1";
option java_multiple_files = true;
option java_outer_classname = "MessageProto";
option ruby_package = "Temporalio::Api::Workflow::V1";
option csharp_namespace = "Temporalio.Api.Workflow.V1";

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

import "dependencies/gogoproto/gogo.proto";

import "temporal/api/enums/v1/workflow.proto";
import "temporal/api/common/v1/message.proto";
import "temporal/api/failure/v1/message.proto";
import "temporal/api/taskqueue/v1/message.proto";

message WorkflowExecutionInfo {
    temporal.api.common.v1.WorkflowExecution execution = 1;
    temporal.api.common.v1.WorkflowType type = 2;
    google.protobuf.Timestamp start_time = 3 [(gogoproto.stdtime) = true];
    google.protobuf.Timestamp close_time = 4 [(gogoproto.stdtime) = true];
    temporal.api.enums.v1.WorkflowExecutionStatus status = 5;
    int64 history_length = 6;
    string parent_namespace_id = 7;
    temporal.api.common.v1.WorkflowExecution parent_execution = 8;
    google.protobuf.Timestamp execution_time = 9 [(gogoproto.stdtime) = true];
    temporal.api.common.v1.Memo memo = 10;
    temporal.api.common.v1.SearchAttributes search_attributes = 11;
    ResetPoints auto_reset_points = 12;
    string task_queue = 13;
    int64 state_transition_count = 14;
    int64 history_size_bytes = 15;
    // If set, the most recent worker version stamp that appeared in a workflow task completion
    temporal.api.common.v1.WorkerVersionStamp most_recent_worker_version_stamp = 16;
}
```

would get compiled like that

```ocaml
(************************************************)
(*       AUTOGENERATED FILE - DO NOT EDIT!      *)
(************************************************)
(* Generated by: ocaml-protoc-plugin            *)
(* https://github.com/issuu/ocaml-protoc-plugin *)
(************************************************)
(*
  Source: v1/message.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot='[@@deriving sexp]'
    opens=[Google_types]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
*)

open Ocaml_protoc_plugin.Runtime [@@warning "-33"]
open Google_types [@@warning "-33"]
(**/**)
module Imported'modules = struct
  module Duration = Duration
  module Timestamp = Timestamp
  module Gogo = Gogo
  module Workflow = Workflow
  module Message = Message
  module Message = Message
  module Message = Message
end
(**/**)
module Temporal = struct
  module Api = struct
    module Workflow = struct
      module V1 = struct
        module rec WorkflowExecutionInfo : sig
…
```
---
@andersfugmann 
I will try to implement a solution. Currently the parameter `ocaml_out` is assumed to be a directory, and in this case the system will produce one file per input files. 

A solution to your setup could be to change the interpretation of the `ocaml_out` flag. If its a file, all "implementation" will be placed into that file. So in your case you could have all files translated in one invocation, and there would be no ambiguity. 

This will also require an extra flag to allow specifying complete "implementations", i.e. if google types implementation resides in a single file, all references to google types would be from this module (i.e. `ocaml_package=google=Google_single_file` or similar to indicate that any module in toplevel `google` should reference `Google_single_file`. Alternatively we could just completely omit any internal module and assume that the modules are available externally. I'll sketch out the details while implementing.

@vbmithr Would this solution work for you. I.e. would you be able to compile all protobuf files in one single invocation, listing all `.proto` files under `temporal` to be compiled into a single file `temporal.ml` that would then contain everything?

(Note that once Dune supports [`include_dirs qualified`](https://discuss.ocaml.org/t/upcoming-dune-feature-include-subdirs-qualified/10891), that would render this new behaviour obsolete but I dont know when that will be implemented.) 

---
@vbmithr
I managed to hack a solution in my fork which works for my use case. Basically I use the fully qualified name for modules names I generate instead of wrapping modules inside the file. I'll try to explain in more details later but if you look at my implementation you will surely understand my changes.

Thanks for thinking at this!

https://github.com/deepmarker/ocaml-protoc-plugin/tree/vb

**Comment by andersfugmann** [comment]
@vbmithr, I have conjured a solution where the emitted modules are prefixed with the package inside the proto file. To examplify:

For the proto file `b.proto`:
```proto
syntax = "proto3";
package Package.A
message B {}
```

The plugin will create a file named `package_a_b`. All imports will assume this mapping, which means that any included proto file will also need to be compiled with the new name mapping.

The behaviour is controlled though the boolean option `prefix_output_with_package`. 

Would this solve the problems you are seeing? 

I did take a look at your changes, but It was hard to get a clear view of your proposed solution. There were some good cleanups and refactorings also. Would you consider upstreaming some of the cleanups?

**Comment by rauanmayemir** [comment]
@andersfugmann I tried `main` branch and the files are not generated with package name prefixed. 🥲 
But `Imported'modules` are indeed correctly using 'fully qualified' module names.

**Comment by andersfugmann** [comment]
Strange. I was sure that was happening. I'll reopen the issue and take a second pass at this.
Thanks for reporting

**Comment by andersfugmann** [comment]
Looking brifely at this - there are test cases covering this and they pass and prefix the filenames with their package name.
E.g.

`basic.proto`:
```proto
syntax = "proto3";

package protoc.plugin.test;

message Message {
    int32 payload = 1;
}
```
 
compiled with `--ocaml_out=prefix_output_with_package=true:.`
Generates the file `protoc_plugin_test_basic.ml`. You can see the dune rule [here](https://github.com/andersfugmann/ocaml-protoc-plugin/blob/314bdacaf04c8f5dd828f868090cbb56799292a8/test/dune#L66).

**Comment by rauanmayemir** [comment]
@andersfugmann What I discovered is that:

- Case A. If you have all your protos flat in a single dir, e.g I tried it with WKT protos, then they're generated correctly with package name prefixed.
- Case B. If you have a tree of protos as `package/name/message.proto`, then they won't be generated as `Package_name_message.ml`. There doesn't seem to be a test case covering this scenario. I.e something like `protoc -I root_dir package/name/message.proto`

**Comment by andersfugmann** [comment]
Thanks for the quick reply. I'll add a testcase as suggested.

**Comment by andersfugmann** [comment]
Bug discovered and solved in #18. I'll merge as soon as the PR is green.

**Comment by andersfugmann** [comment]
@rauanmayemir Could you retest to verify that the solution works for you?

**Comment by rauanmayemir** [comment]
@andersfugmann Retested, now it works as expected. 👍👍👍

**Comment by andersfugmann** [comment]
Thanks for verifying.
